import { config } from '@fortawesome/fontawesome-svg-core';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import Navbar from '@/components/Navbar';

import '@fortawesome/fontawesome-svg-core/styles.css';
import '../../globals.css';

config.autoAddCss = false;

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'PleasedHome',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="flex min-h-screen flex-col">
          <Navbar variant={'navbar-form'}></Navbar>
          <main className="flex flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
